services:
  cloudflare-tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cf-tunnel
    depends_on:
      - 'logger'
    command:
      - tunnel
      - --no-autoupdate
      - run
      - --token
      - ${CLOUDFLARE_TOKEN}
    restart: unless-stopped

  logger:
    image: python:3.14-alpine
    container_name: heartbeat-logger
    volumes:
      - .:/app
    working_dir: /app
    command: python -OO heartbeat_logger.py
    restart: unless-stopped

  simplefileserver:
    build:
      context: ./simplefileserver
    container_name: simplefileserver
    restart: always